on:
  pull_request:
  workflow_dispatch:
#  push:
#    branches:
#      - develop-lx
name: "Tests"
permissions:
  pull-requests: write
jobs:
  gtest:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: cd test && pip install -r requirements.txt
      - name: Build
        run: |
          cmake -DTEST=on -Bbuild && cmake --build build --target all
      - name: Make Data
        run:
          cd test && bash test.sh
      - name: Test
        uses: gacts/run-and-post-run@v1
        env:
          FEISHU_TOKEN: ${{ secrets.FEISHU_TOKEN }}
          FEISHU_AT: ${{ secrets.FEISHU_AT }}
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          working-directory: bin
          run: ls && ./MLLM_TEST --gtest_output=json
          post: |
            COMMIT_MESSAGE="$(git show -s --format=%s)" python3 ../tools/ci/report.py
          
        

    
